<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotivoAdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $motivos = [

            [
                'codigo' => '7',
                'codigoMotivo' => 'M04',
                'descricao' => 'IVA – Regime de não sujeição',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '8',
                'codigoMotivo' => 'M02',
                'descricao' => 'Transmissão de bens e serviço não sujeita',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '9',
                'codigoMotivo' => 'M00',
                'descricao' => 'Regime Transitório',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '10',
                'codigoMotivo' => 'M10',
                'descricao' => 'Isento nos termos da alínea a) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '11',
                'codigoMotivo' => 'M11',
                'descricao' => 'Isento nos termos da alínea b) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '12',
                'codigoMotivo' => 'M12',
                'descricao' => 'Isento nos termos da alínea c) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '13',
                'codigoMotivo' => 'M13',
                'descricao' => 'Isento nos termos da alínea d) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '14',
                'codigoMotivo' => 'M14',
                'descricao' => 'Isento nos termos da alínea e) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '15',
                'codigoMotivo' => 'M15',
                'descricao' => 'Isento nos termos da alínea f) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '16',
                'codigoMotivo' => 'M16',
                'descricao' => 'Isento nos termos da alínea g) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '17',
                'codigoMotivo' => 'M17',
                'descricao' => 'Isento nos termos da alínea h) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '18',
                'codigoMotivo' => 'M18',
                'descricao' => 'Isento nos termos da alínea i) do nº1 artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '19',
                'codigoMotivo' => 'M19',
                'descricao' => 'Isento nos termos da alínea j) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '20',
                'codigoMotivo' => 'M20',
                'descricao' => '0 Isento nos termos da alínea k) do nº1 do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '21',
                'codigoMotivo' => 'M21',
                'descricao' => 'Isento nos termos da alínea l) do nº1 do artigo 12.º do CIVA
',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '22',
                'codigoMotivo' => 'M22',
                'descricao' => 'Isento nos termos da alínea m) do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '23',
                'codigoMotivo' => 'M23',
                'descricao' => 'Isento nos termos da alínea n) do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '24',
                'codigoMotivo' => 'M24',
                'descricao' => 'Isento nos termos da alínea 0) do artigo 12.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '25',
                'codigoMotivo' => 'M80',
                'descricao' => 'Isento nos termos da alínea a) do nº1 do artigo 14.º ',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '26',
                'codigoMotivo' => 'M81',
                'descricao' => 'Isento nos termos da alínea b) do nº1 do artigo 14.º ',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '27',
                'codigoMotivo' => 'M82',
                'descricao' => 'Isento nos termos da alínea c) do nº1 do artigo 14.º ',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '28',
                'codigoMotivo' => 'M83',
                'descricao' => 'Isento nos termos da alínea d) do nº1 do artigo 14.º ',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '29',
                'codigoMotivo' => 'M84',
                'descricao' => 'Isento nos termos da alínea e) do nº1 do artigo 14.º ',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '30',
                'codigoMotivo' => 'M85',
                'descricao' => 'Isento nos termos da alínea a) do nº2 do artigo 14.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '31',
                'codigoMotivo' => 'M86',
                'descricao' => 'Isento nos termos da alínea b) do nº2 do artigo 14.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '32',
                'codigoMotivo' => 'M30',
                'descricao' => 'Isento nos termos da alínea a) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '33',
                'codigoMotivo' => 'M31',
                'descricao' => 'Isento nos termos da alínea b) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '34',
                'codigoMotivo' => 'M32',
                'descricao' => 'Isento nos termos da alínea c) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '35',
                'codigoMotivo' => 'M33',
                'descricao' => 'Isento nos termos da alínea d) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '36',
                'codigoMotivo' => 'M34',
                'descricao' => 'Isento nos termos da alínea e) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '37',
                'codigoMotivo' => 'M35',
                'descricao' => 'Isento nos termos da alínea f) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '38',
                'codigoMotivo' => 'M36',
                'descricao' => 'Isento nos termos da alínea g) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '39',
                'codigoMotivo' => 'M37',
                'descricao' => 'Isento nos termos da alínea h) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '40',
                'codigoMotivo' => 'M38',
                'descricao' => 'Isento nos termos da alínea i) do artigo 15.º do CIVA',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '41',
                'codigoMotivo' => 'M90',
                'descricao' => 'Isento nos termos da alínea a) do nº1 do artigo 16.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '42',
                'codigoMotivo' => 'M91',
                'descricao' => 'Isento nos termos da alínea b) do nº1 do artigo 16.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '43',
                'codigoMotivo' => 'M92',
                'descricao' => 'Isento nos termos da alínea c) do nº1 do artigo 16.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '44',
                'codigoMotivo' => 'M93',
                'descricao' => 'Isento nos termos da alínea d) do nº1 do artigo 16.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ], [
                'codigo' => '45',
                'codigoMotivo' => 'M94',
                'descricao' => 'Isento nos termos da alínea e) do nº1 do artigo 16.º',
                'codigoStatus' => 1,
                'user_id' => 1,
                'canal_id' => 1,
                'status_id' => 1,
                'empresa_id' => null,
                'created_at' => '2020-04-23 20:56:46',
                'updated_at' => '2020-04-23 20:56:46',
            ],
        ];

        foreach ($motivos as $motivo) {
            $motivo = (object)$motivo;
            DB::connection('mysql')->table('motivo')->insert([
                'codigo' => $motivo->codigo,
                'codigoMotivo' => $motivo->codigoMotivo,
                'descricao' => $motivo->descricao,
                'codigoStatus' => $motivo->codigoStatus,
                'canal_id' => $motivo->canal_id,
                'user_id' => $motivo->user_id,
                'status_id' => $motivo->status_id,
                'empresa_id' => $motivo->empresa_id,
                'created_at' => $motivo->created_at,
                'updated_at' => $motivo->updated_at,
            ]);
        }
    }
}
